### ISSUE TITLE
Couldn't parse loot table macawsbridgesenhancedmushrooms:blocks/rope_glowshroom_bridge

### ISSUE THREAD

**Issue by curryducker** [Samlegamer/Macaw-s-Bridges-Compat#12]
This is an error i get when using the Macaw's Bridges - Enhanced Mushrooms mod. Seems like the rope glowshroom bridge doesn't even exist?
![image](https://user-images.githubusercontent.com/66020230/178139092-1564ac05-6ae0-4523-b069-66ee4ca65678.png)

Happens on: macawsbridgesenhancedmushrooms-1.16.5-1.2
forge 36.2.34

**Comment by Samlegamer** [comment]
Fixed in the new addons Macaw's Bridges - Aurora
