### ISSUE TITLE
1.16.5 Downloads TerraBlender for 1.19.2 Crashing the game

### ISSUE THREAD

**Issue by Bethylee** [Samlegamer/Macaw-s-Bridges-Compat#14]
Macaw's Bridges 1.16.5 v. 2.3 Downloads TerraBlender-forge-1.19.2-2.0.1.128.jar automatically on CurseForge which is incompatible. Hopefully I did it right, but there should be Two Images attached and the crash log. One of the images is just the mods list for reference.

[crash-2022-11-04_17.29.10-fml.txt](https://github.com/Samlegamer/Macaw-s-Bridges-Compat/files/9942601/crash-2022-11-04_17.29.10-fml.txt)
![Crash](https://user-images.githubusercontent.com/24442876/200093322-3b19bf31-0472-46b2-b073-2123995a2caa.png)
![pixelmon mods list](https://user-images.githubusercontent.com/24442876/200093323-51890436-a67c-4743-bd8a-85302099024b.png)

**Comment by Samlegamer** [comment]
It does it for me too, just removing TerraBlender-forge-1.19.2-2.0.1.128.jar makes the game start without any problem.
![imgmcw](https://user-images.githubusercontent.com/83614614/200133771-093bcd6b-f45a-4d6b-83bf-cf437bd3017d.PNG)

**Comment by Samlegamer** [comment]
Quite strange that it downloads Terrablender, I have looked at no mod mentioning it though

**Comment by Bethylee** [comment]
The only thing I could think of is something to do with terrablender being
a dependency for 1.18 and 1.19 and curse forge tagging 1.16.5 as needing it
as well?

**Comment by Samlegamer** [comment]
it is not mentioned in the 1.16.5 updates though...
