### ISSUE TITLE
Missing Textures - Fabric 1.19.2

### ISSUE THREAD

**Issue by AutoRunFail** [Samlegamer/Macaw-s-Bridges-Compat#18]
There are several missing textures in the 1.19.2 Fabric version of the mod. I noticed the Forge version was recently updated to fix this issue and was hoping the Fabric version could be updated as well.

Mod Version:  **1.19.2 - 1.0** version of Macaw's Bridge BYG Compat 

Fabric Loader Version:  **0.14.10**

Fabric API Version:  **0.69.0**

Minecraft Version: **1.19.2**

![Screenshot- BYG Macaw Bridge](https://user-images.githubusercontent.com/105956312/210307793-b8736465-f532-46fb-8bb2-ee4280820dcd.png)

**Comment by Samlegamer** [comment]
fixed in **_macawsbridgesbyg-fabric-1.19.2-1.0_**

https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-oh-the-biomes-youll-go/files/4293589
