### ISSUE TITLE
Macaw's Bridges Buzzier Bees not yet updated for Macaw's Bridges 2.0.0

### ISSUE THREAD

**Issue by Brycey92** [Samlegamer/Macaw-s-Bridges-Compat#2]
[crash-2021-11-18_20.44.47-fml.txt](https://github.com/Samlegamer/Macaw-s-Bridges-Compat/files/7567200/crash-2021-11-18_20.44.47-fml.txt)

**Comment by Samlegamer** [comment]
Updated!

**Comment by Brycey92** [comment]
Many thanks!
