### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Herobattler** [Samlegamer/Macaw-s-Bridges-Compat#20]
The error message states that various entity models like minecraft:witch are missing

**Comment by Herobattler** [comment]
[Uploading crash-2023-04-03_16.19.42-client.txt…]()

**Comment by Herobattler** [comment]
[crash-2023-04-03_16.19.42-client.txt](https://github.com/Samlegamer/Macaw-s-Bridges-Compat/files/11148502/crash-2023-04-03_16.19.42-client.txt)

**Comment by Samlegamer** [comment]
It seems that it is a client side mod only that does this.

**Comment by Herobattler** [comment]
Issue disappeared without a trace

**Comment by Herobattler** [comment]
Not reproducable
