### ISSUE TITLE
target exception zero crash

### ISSUE THREAD

**Issue by Herobattler** [Samlegamer/Macaw-s-Bridges-Compat#21]
[crash-2023-04-05_09.59.20-fml.txt](https://github.com/Samlegamer/Macaw-s-Bridges-Compat/files/11156494/crash-2023-04-05_09.59.20-fml.txt)

**Comment by Samlegamer** [comment]
Macaw's Bridges Mod is missing : https://www.curseforge.com/minecraft/mc-mods/macaws-bridges
