### ISSUE TITLE
Failed to Load correctly

### ISSUE THREAD

**Issue by lynxaradev** [Samlegamer/Macaw-s-Bridges-Compat#26]
Ver: 1.19.2
All the BOP/BYG mods failed to load correctly. Tested with only BOP, only BYG and together.

Report:
[crash-2023-11-23_10.28.48-fml.txt](https://github.com/Samlegamer/Macaw-s-Bridges-Compat/files/13447964/crash-2023-11-23_10.28.48-fml.txt)

**Comment by Samlegamer** [comment]
if you don't have Macaw's Bridges installed, you'll need Macaw's Roofs for compatibility too.

https://legacy.curseforge.com/minecraft/mc-mods/macaws-bridges/files/4671055
https://legacy.curseforge.com/minecraft/mc-mods/macaws-roofs/files/4671061

**Comment by lynxaradev** [comment]
Ok, I see it. The problem is that Modrinth doesn't have comp. add-ons

**Comment by lynxaradev** [comment]
Tips for those that find this error. Download Macaw mods separately from Curseforge if there are not still added to Modrinth when you see this issue.
