### ISSUE TITLE
Macaw's Bridges Oh The Biomes You'll Go not yet updated for Macaw's Bridges 2.0.0

### ISSUE THREAD

**Issue by Brycey92** [Samlegamer/Macaw-s-Bridges-Compat#3]
[crash-2021-11-18_20.48.21-fml.txt](https://github.com/Samlegamer/Macaw-s-Bridges-Compat/files/7567218/crash-2021-11-18_20.48.21-fml.txt)

**Comment by Samlegamer** [comment]
Hello, this is exactly what is written on these mods.
![macaws](https://user-images.githubusercontent.com/83614614/142571672-f4d52e15-06be-4d11-a1e9-f84e349f1e15.PNG)

**Comment by Brycey92** [comment]
Oh oops! How did I miss that giant bold text? :joy: :sweat_smile:

**Comment by Samlegamer** [comment]
Updated!

**Comment by Brycey92** [comment]
Thanks!
