### ISSUE TITLE
Mods are missing "Rope WOODTYPE Bridge Stair" variant

### ISSUE THREAD

**Issue by brnbrd** [Samlegamer/Macaw-s-Bridges-Compat#6]
None of the mods here have the 6th block variant from Macaw's Bridges, the Rope WOODTYPE Bridge Stair. It is absent from the files. It's model should belong in  block/stair/rope.

**Comment by Samlegamer** [comment]
I have added in the last update of Biomes O' Plenty and Oh The Biome You'll Go compatibility.

Remaining :

Autumnity
Atmospheric
Bayou Blues
Enhanced Mushrooms
Environmental
Shroomed

**Comment by Samlegamer** [comment]
it's done ✅
